### ISSUE TITLE
Can't see action buttons for the bottom article

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#22]
When touching the last article on the list, you can't see the area where it expands to show the play & skim buttons. We need to scroll that into view after the expansion.

**Comment by Alegero** [comment]
done

**Comment by dylano** [comment]
This does work now for the very last article on the list, although the collapse action when clicking the article a second time to hide the buttons isn't smooth like it is for other articles in the list.

But I still see this problem behavior for articles which are not the last article. For example for the 9th out of 10 list items which is positioned at the bottom of the screen, touching here does not scroll the buttons into view so it is not clear any action has been taken.

**Comment by dylano** [comment]
There's a new issue here: 
* scroll down to last article 
* click to show action buttons
* click again to hide action buttons
* now start clicking on articles higher in the list (but don't scroll all the way to the top)

Result: the article list starts scrolling up a few pixels with each click

Video: https://photos.app.goo.gl/gwBjo66HL0wfGLBg2

**Comment by iukhno** [comment]
hi @dylano this behaviur happens because we should scroll screen a bit when user try to see last item on the list. this is specific behaviour. we have 2 options here:
- we could keep as it is now and process case of opening last item's bar
- we can remove showing last item's panel in case user click on it (user will have to scroll by himlef to see it) and this movement would be stopped 
please suggest

**Comment by dylano** [comment]
@iukhno With build 14 this doesn't seem to be related to the last item anymore. If I scroll down anywhere past the second article in the list and the repeatedly click to expand and collapse the action section on any of the articles, the list slowly scrolls upward a couple of pixels at a time with each click. 

I understand that it's related to the changes that were made for the last item on the list, but this is a strange behavior. I think we should continue trying to fix it.

**Comment by Alegero** [comment]
done
